name: Video_Analyse
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - expat=2.7.1
  - libcxx=19.1.7
  - libffi=3.4.4
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.2
  - python=3.12.11
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - altgraph==0.17.4
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - decorator==4.4.2
      - idna==3.11
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - macholib==1.16.3
      - moviepy==1.0.3
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pillow==11.3.0
      - proglog==0.1.12
      - pyinstaller==6.16.0
      - pyinstaller-hooks-contrib==2025.9
      - pyside6==6.10.0
      - pyside6-addons==6.10.0
      - pyside6-essentials==6.10.0
      - python-dotenv==1.2.1
      - requests==2.32.5
      - shiboken6==6.10.0
      - tqdm==4.67.1
      - urllib3==2.5.0
prefix: /Users/max/miniforge3/envs/Video_Analyse
